### ISSUE TITLE
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by RincewindWizzard** [t-oster/LibLaserCut#45]
When using Visicut 1.7.9-23-g46d8904 there is an exception thrown, when calculating the duration of engraving. Seems like a problem with implicit/explicit casts. Should be fixed with:
`Integer intVal = (Float value).intValue();`
> java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at com.t_oster.liblasercut.PowerSpeedFocusProperty.setProperty(PowerSpeedFocusProperty.java:137)
	at com.t_oster.liblasercut.RasterPart.<init>(RasterPart.java:43)
	at com.t_oster.visicut.model.RasterProfile.addToLaserJob(RasterProfile.java:230)
	at com.t_oster.visicut.VisicutModel.prepareJob(VisicutModel.java:737)
	at com.t_oster.visicut.VisicutModel.estimateTime(VisicutModel.java:787)
	at com.t_oster.visicut.gui.MainView$66.run(MainView.java:2625)

**Comment by t-oster** [comment]
Do you have any old lasercutter configfiles present? Please retry with cleared ".visicut" folder

**Comment by madleech** [comment]
Oops that would be my fault. Fixed in PR #46

**Comment by AbdelhadiBaben** [comment]
try : 
          int x = ((**Number**) floatVal).intValue();

**Comment by mgmax** [comment]
Please provide some context: does the bug still occur for you with the newest VisiCut 1.8.x?
